version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: tracee-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-interface-service:
    build: mongo/
    container_name: mongo-interface-service
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      DB_NAME: tracee_analysis
    ports:
      - "8001:8001"

  mcp-service:
    build: mcp/
    container_name: mcp-service
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      DB_NAME: tracee_analysis
    ports:
      - "8001:8001"



volumes:
  mongo_data:
